package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio
import static com.pedropathing.api.Paths.*;

import com.pedropathing.paths.Path;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.ivy.Scheduler;

import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.groups.Groups.sequential;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;

@Autonomous
public class BasicAuto extends OpMode {
    private Follower follower; // Add this
    private final PoseFactory p = PoseFactory.degrees();

    // Robot dimensions (in), measured from the robot's center
    private static final double W = 7.25;
    private static final double L = 8.25;

    private static final double HEADING = 180;

    private final Pose startPose = p.of(24, 144 - L, HEADING);   // Starts facing the wall
    private final Pose flowerAccess = p.of(24, 138 - L, HEADING); // Moves out to access flower
    private final Pose flower = p.of(48, 138 - L, HEADING);       // Moves to flower
    private final Pose collect = p.of(48, 140 - L, HEADING);      // Moves to collect flower
    private final Pose park = p.of(12, 120, HEADING);             // Moves to park

    private Path move(Pose from, Pose to) {
        return line(from, to).constant(HEADING);
    }

    @Override
    public void init() {
        Scheduler.reset();

        follower = Constants.create(hardwareMap);
        follower.setPose(startPose);
    }

    @Override
    public void start() {
        schedule(sequential(
                follow(follower, move(startPose, flowerAccess)),
                follow(follower, move(flowerAccess, flower)),
                follow(follower, move(flower, collect)),
                follow(follower, move(collect, park))
        ));
    }

    @Override
    public void loop() {
        follower.update();
        Scheduler.execute();
    }
}
